# Generated by Django 3.2.7 on 2021-09-23 04:42

import atm.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SuperUser')),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ['id'],
            },
            managers=[
                ('objects', atm.models.ActiveUserManager()),
                ('all_objects', atm.models.ActiveObjectsManager()),
                ('all_delete_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
