# Generated by Django 3.2.5 on 2021-09-25 02:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='street')),
                ('housenumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='house number')),
                ('postalcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='geo location')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('openingHours', models.TextField(blank=True, null=True)),
                ('functionality', models.CharField(blank=True, max_length=50, null=True, verbose_name='funtionality')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='type of ATM')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'abstract': False,
                'index_together': {('created_at', 'updated_at')},
            },
        ),
    ]
