# Generated by Django 3.2.5 on 2021-09-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0003_alter_atmdetails_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmdetails',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
